# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
isolated_build = true
envlist =
    2.7,
    3.4,
    3.5,
    3.6,
    3.7,
    3.8,
#    pypy,
#    pypy3,

[testenv]
whitelist_externals = poetry
commands =
    poetry install -v
    spec
